"""add_teamsnap_columns_and_links

Revision ID: 74fa852e10fb
Revises: b3610d4bf24a
Create Date: 2026-05-16 22:09:18.912161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74fa852e10fb'
down_revision: Union[str, Sequence[str], None] = 'b3610d4bf24a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teamsnap_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('teamsnap_team_id', sa.String(), nullable=False),
    sa.Column('teamsnap_team_name', sa.String(), nullable=False),
    sa.Column('ncsa_subscription_id', sa.Integer(), nullable=True),
    sa.Column('roster_json', sa.Text(), nullable=True),
    sa.Column('roster_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ncsa_subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teamsnap_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('teamsnap_access_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('teamsnap_refresh_token', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_teamsnap_id'), ['teamsnap_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_teamsnap_id'))
        batch_op.drop_column('teamsnap_refresh_token')
        batch_op.drop_column('teamsnap_access_token')
        batch_op.drop_column('teamsnap_id')

    op.drop_table('teamsnap_links')
    # ### end Alembic commands ###
